apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibench-small-interference
  labels:
    app: ibench-small-interference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibench-small-interference
  template:
    metadata:
      labels:
        app: ibench-small-interference
    spec:
      containers:
      - name: ibench-cpu
        image: stav1212/ibench:latest
        command: ["./cpu"]
        args: ["14400"]  
        resources:
          requests:
            cpu: "1"     
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
